version: "3.7"

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
  database:
    container_name: database
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
